### ISSUE TITLE
DLL 버전 문의

### ISSUE THREAD

**Issue by mrchypark** [bab2min/kiwi-gui#2]
현재 kiwi 모듈의 버전은 0.8.2 인데요.

본 레포의 relaese 는 0.7.0까지 인 것 같습니다.

버전 컨벤션이 다른 것인지, 혹은 이 레포는 더 이상 유지 보수 하지 않으시는 건지 궁금합니다.

**Comment by bab2min** [comment]
사실은 현재 제공하는 c# wrapper가 윈도우 native dll에 의존적이라 유니버셜하지 못하다는 문제가 있어서 현재 방법으로 계속 C# wrapper를 제공하는게 옳을지 고민중에 있습니다. 그래서 0.8 버전 이후로 업데이트를 진행하지 않고 있는데요, 방향성 결정되면 새로 업데이트를 진행하든지 정리하도록 할 예정입니다.

**Comment by mrchypark** [comment]
알겠습니다. 답변 감사드립니다.  :)

2020년 11월 3일 (화) 오후 9:14, bab2min <notifications@github.com>님이 작성:

**Comment by bab2min** [comment]
@mrchypark 조금 많이 지나긴 했습니다만, 기존과 같이 c# wrapper를 제공하는 것으로 방향을 결정하였습니다.
최신 버전인 0.10.1의 KiwiGui를 업로드했으니 필요하시다면 아래 링크에서 다운 받으실 수 있습니다.
https://github.com/bab2min/kiwi-gui/releases/tag/v0.10.1
