### ISSUE TITLE
Update to latest version?

### ISSUE THREAD

**Issue by valdirSalgueiro** [bab2min/kiwi-gui#7]
Any chance to update to latest version 0.17.1?
Thanks

**Comment by bab2min** [comment]
Hi, @valdirSalgueiro 
Thank you for your interest in KiwiGui.
I was so busy that I missed the update, but I just uploaded the releases from v0.15.2 to v0.17.1.

**Comment by valdirSalgueiro** [comment]
Thanks for the prompt response :)

one question is this related to version or configuration? I can't get the same result from web in gui for this word even after I updated to latest version:
![image](https://github.com/bab2min/kiwi-gui/assets/858374/d6675ba7-76aa-4ef9-946d-0cda11727217)

web version:
![image](https://github.com/bab2min/kiwi-gui/assets/858374/fdeb856e-aad5-4848-a562-362e136dfccd)

sorry if this is another question
